version: '3.9'

services:

  thmho-ros-ngsi:
    network_mode: "host"
    depends_on: 
      - orion
    image: thmho-heatmap-ngsi
    container_name: thmho-heatmap-ngsi
    volumes:
      - ./entrypoint-ngsi.sh:/entrypoint.sh

  thmho-ros-server:
    network_mode: "host"
    image: thmho-heatmap-server
    container_name: thmho-heatmap-server
    volumes:
      - ./entrypoint-server.sh:/entrypoint.sh

  mongo-orion:
    image: mongo:4.4
    command: --nojournal

  orion:
    image: fiware/orion
    links:
      - mongo-orion
    ports:
      - "1026:1026"
    command: -dbhost mongo-orion

  mongo:
    container_name: mongo
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ../src/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
      - mgstorage:/data/db

  flask:
    build:
      context: .
      dockerfile: Dockerfile-flask
    container_name: flask
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_COLLECTION=${MONGO_COLLECTION}
      - HEATMAP_WIDTH=${HEATMAP_WIDTH}
      - HEATMAP_HEIGHT=${HEATMAP_HEIGHT}
    image: flask
    ports:
      - 5000:5000
    depends_on:
      - mongo
    volumes:
      - ../src/flask:/src

  dash:
    build:
      context: .
      dockerfile: Dockerfile-dash
    container_name: dash
    environment:
      - MONGO_INITDB_DATABASE=heatmap
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=admin
      - MONGO_COLLECTION=${MONGO_COLLECTION}
      - HEATMAP_WIDTH=${HEATMAP_WIDTH}
      - HEATMAP_HEIGHT=${HEATMAP_HEIGHT}
    image: dash
    ports:
      - 8050:8050
    depends_on:
      - flask
    volumes:
      - ../src/dash:/src

volumes:
  mgstorage:
    external: true



